# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_solve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='prob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Problem'),
        ),
    ]
