# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_auto_20170504_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solver',
        ),
    ]
