# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_remove_problem_solver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logmsg', models.TextField()),
                ('created_data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
