# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
