# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_delete_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='comment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
